<?php

/*
 * takes care of
 *  - drupal_projects
 *  - drupal_projects_page
 *  - personal_profile
 *  - personal_profile_page
 *  - ufal_tool
 *  - ufal_tool_page
 *  
 *  content types
 */

function drupal_projects_node_info() {

	$items['drupal_projects'] = array(
			'name' => t('Project'),    // name of your content type
			'type' => 'drupal_projects',
			'base' => 'node_content',
			'description' => t('Project pages form a section of UFAL pages with own logo, slogan and main menu. UFAL logo in the right hand side of the header and a first link in main menu provide means of returning back to the UFAL homepage. Each project resides in an aptly named subdirectory.'),
			'has_title' => '1',
			'title_label' => t('Project name'),
			'body_label' => t('Homepage content'),
			//'help' => t('Please fill in all fields.'),
			'locked' => true,
	);
	
	$items['drupal_projects_page'] = array(
			'name' => t('Subpage'),    // name of your content type
			'type' => 'drupal_projects_page',
			'base' => 'node_content',
			'description' => t('Add an additional page into an existing project.'),
			'has_title' => '1',
			'title_label' => t('Page title'),
			'body_label' => t('Page content'),
			//'help' => t('Please fill in all fields.'),
			'locked' => true,
	);

	return $items;
}

function drupal_projects_form($node, $form_state) {
	return node_content_form($node, $form_state);
}

/**
 * Implements hook_init
 */
function drupal_projects_init() {
	/**
	 * force public project urls ending in trailing slash
	 * so relative links work as expected (ie. relative to the project url)
	 */
	if (!path_is_admin(current_path())) {
		$node = menu_get_object();
		
		if (!empty($node) && $node->type == 'drupal_projects') {
			$acronym = _project_to_acronym($node);
			$slug = _project_slug($acronym);
			$path = $slug . '/';
			// try to avoid redirect loop
			if (strpos($_SERVER['REQUEST_URI'], $path) === false) {
				return drupal_goto($path, $options = array(), $http_response_code = 301);
			}
		}
	}
}

/**
 * Implements hook_node_insert().
 * 
 * new project needs own menu
 * new project needs shortcut
 * $node already has $node->nid
 */
function drupal_projects_node_insert($node) {
	$t = get_t();
	
	if (preg_match('/^(drupal_projects|personal_profile|ufal_tool)$/', $node->type)) {
		// create a new menu for the project minisite
		$menu = _project_to_menu_array($node);
		if (!menu_load($menu['menu_name'])) {
			menu_save($menu);
			// allow this menu for relevant subpage content type
			// otherwise you could put pages there
			$allowed_menus = variable_get('menu_options_'.$node->type.'_page');
			$allowed_menus[]  = $menu['menu_name'];
			variable_set('menu_options_'.$node->type.'_page', $allowed_menus);
		}
		
		// find coresponding term
		$term = _project_to_term($node);
		
		// workbench access
		_workbench_access_allow_user_access_to_project($term->tid);
		
		// add it to the shortcuts
		$shortcut_set = shortcut_set_load(variable_get('drupal_projects_shortcut_set_name'));
		if ($shortcut_set && $term->tid) {
			$shortcut_link = array(
				'link_path' => 'admin/my-content/' . $term->tid,
				'link_title' => _project_to_acronym($node),
				'weight' => -20,
				'menu_name' => $shortcut_set->set_name,
				'plid' => 0,
				'module'  => 'drupal_projects'
			);
			menu_link_save($shortcut_link);
			menu_cache_clear_all();
		}
	}
}

/**
 * a node being inserted or updated.
 *  - project term in right vocabulary (projects/profiles/tools)
 *  - auto path
 *  - 
 */

function drupal_projects_node_presave($node) {
	$t = get_t();
	if (preg_match('/^(drupal_projects|personal_profile|ufal_tool)$/', $node->type)) {
		// derive path from acronym field
		// TODO test for user filled path here!!
		$acronym = _project_to_acronym($node);
		$node->path['alias'] = _project_slug($acronym);
		$node->path['pathauto'] = 0;
		
		// taxonomy classification
		if (isset($node->original) && _project_to_term_tid($node->original)) {
			drupal_projects_term_update($node, $node->original);
		} else {
			$project_term = drupal_projects_term_create($node);
			_attach_node_to_project($node, $project_term);
		}
		
		// update the menu for the project minisite
		if (isset($node->original)) {
			$menu = _project_to_menu_array($node->original);
			if (menu_load($menu['menu_name'])) {
				// new menu, but got same menu name
				$menu = _project_to_menu_array($node);
				menu_save($menu);
			}
		}
		
		// if acronym has changed, so did project URI
		// we have to update all subpage menu items
		if (isset($node->original)) {
			$old_slug = _project_slug(_project_to_acronym($node->original));
			$new_slug = _project_slug(_project_to_acronym($node));
			$result = _project_get_url_aliases($node->original);
			foreach ($result as $path) {
				$pattern = '^' . $old_slug . '\/';
				$path['alias'] = preg_replace("/$pattern/", $new_slug . '/', $path['alias']);
				path_save($path);
			}
		}
		
		// shortcut bar update
		if (isset($node->original)) {
			drupal_projects_shortcut_update($node);
		}
	}
	
	if (preg_match('/^(drupal_projects_page|personal_profile_page|ufal_tool_page)$/', $node->type)) {
		// menu has to be expanded
		$node->menu['expanded'] = 1;
		
		// derive path in form [project]/[page]
		$project = _node_to_project($node);
		$acronym = _project_to_acronym($project);
		$node->path['alias'] = _project_slug($acronym) . '/' . _project_slug($node->title);
		$node->path['pathauto'] = 0;
	}
}

function drupal_projects_shortcut_update($node) {
	$shortcut_set = shortcut_set_load(variable_get('drupal_projects_shortcut_set_name'));
	$term_tid = _project_to_term_tid($node);
	$acronym = _project_to_acronym($node);
	
	$result = _project_get_shortcut_links($term_tid);
	foreach ($result as $link) {
		if ($link['link_path'] == 'admin/my-content/' . $term_tid) {
			$link['options']    = unserialize($link['options']);
			$link['link_title'] = $acronym;
			menu_link_save($link);
		}
	}
	menu_cache_clear_all();
}
function drupal_projects_term_update($node, $original_node) {
	$t = get_t();
	// update the taxonomy name upon node change
	$term = _project_to_term($original_node);
	$term->name = $t($node->title);
	taxonomy_term_save($term);
}
function drupal_projects_term_create($node) {
	$t = get_t(); 
	$vocabulary_id = _project_to_vocabulary_id($node);
	$vocabulary    = taxonomy_vocabulary_load($vocabulary_id);
	$terms = taxonomy_get_term_by_name($t($node->title), $vocabulary->machine_name);
	if (count($terms) > 0) {
		// found existing
		$newterm = array_shift($terms);
	} else {
		// add a taxonomy term
		$newterm = new stdClass();
		$newterm->name = $t($node->title);
		$newterm->vid  = $vocabulary_id;
		taxonomy_term_save($newterm);
	}
	return $newterm;
}
function _attach_node_to_project($node, $project_term) {
	// attach node to taxonomy term
	$project_field = _get_project_attachment_field($node);
	$node->{$project_field}[$node->language][$project_term->tid] = (array) $project_term;
}
function _get_project_attachment_field($node) {
	$tx = array(
		'personal_profile' => 'field_profile',
		'drupal_projects'  => 'drupal_projects_project',
		'ufal_tool'        => 'field_project_term',
	);
	$project_field = @$tx[$node->type];
	if (!$project_field) {
		drupal_set_message('no project field defined for ' . $node->type, 'warning');
	}
	return $project_field;
}

/**
 * Implements hook_node_delete().
 */
function drupal_projects_node_delete($node) {
	$t = get_t();
	
	if (preg_match('/^(drupal_projects|personal_profile|ufal_tool)$/', $node->type)) {
		$vocabulary_id = _project_to_vocabulary_id($node);
		$vocabulary    = taxonomy_vocabulary_load($vocabulary_id);
	
		// delete a taxonomy term
		$terms = taxonomy_get_term_by_name($t($node->title), $vocabulary->machine_name);
		if (count($terms) == 1) {
			$term = current($terms);
			taxonomy_term_delete($term->tid);
		}
		// delete shortcut links to project view
		// TODO could be rewritten now!! as link_path contains project_tid now
		$result = _project_get_shortcut_links($term->tid);
		foreach ($result as $link) {
			if ($link['link_path'] == 'admin/my-content/' . $term->tid) {
				menu_link_delete($link['mlid']);
			}
		}
	
		// delete menu for the project minisite
		$menu = _project_to_menu($node);
		if ($menu) {
			// delete all project/profile/tools subpages
			$project_field = _get_project_attachment_field($node);
			$bundle = $node->type . '_page';
			
			$query = new EntityFieldQuery();
			$query->entityCondition('entity_type', 'node')
					->entityCondition('bundle', $bundle)
					->fieldCondition($project_field, 'tid', $term->tid, '=');
			$result = $query->execute();

			if (!empty($result['node'])) {
				$nids = array_keys($result['node']);
				node_delete_multiple($nids);
			}
			
			// last shot
			menu_delete($menu);
			menu_cache_clear_all();
		}
	}
}

/**
 * Implements hook_custom_theme
 */
function drupal_projects_custom_theme() {
	// default theme for admin area
	if (path_is_admin(current_path())) { return; }
	if (preg_match('/user\/\d+/', current_path())) { return; }

	// find out if the current page is part of projects hierarchy
	$node = node_load(arg(1));
	$term = _project_to_term($node);
	
	if (@$term->vid == variable_get('drupal_projects_vocabulary_id')) {
		// we got a project (page)
		return 'drufal_project';
	}
	if (@$term->vid == variable_get('profiles_vocabulary_id')) {
		// we got a personal profile (page)
		menu_tree_set_path('main-menu', 'people');
		return 'drufal_profile';
	}
	if (@$term->vid == variable_get('ufal_tool_vocabulary_id')) {
		// we got a ufal tool (page)
		menu_tree_set_path('main-menu', 'tools');
		return 'drufal_tool';
	}
}

/**
 * Implements hook_image_default_styles().
 *
 * hook_image_default_styles() declares to Drupal any image styles that are
 * provided by the module. An image style is a collection of image effects that
 * are performed in a specified order, manipulating the image and generating a
 * new derivative image.
 *
 * This hook can be used to declare image styles that your module depends on or
 * allow you to define image styles in code and gain the benefits of using
 * a version control system.
 */
function drupal_projects_image_default_styles() {
	// This hook returns an array, each component of which describes an image
	// style. The array keys are the machine-readable image style names and
	// to avoid namespace conflicts should begin with the name of the
	// implementing module. e.g.) 'mymodule_stylename'. Styles names should
	// use only alpha-numeric characters, underscores (_), and hyphens (-).
	$styles = array();
	$styles['drupal_projects_logo_style'] = array();

	// Each style array consists of an 'effects' array that is made up of
	// sub-arrays which define the individual image effects that are combined
	// together to create the image style.
	$styles['drupal_projects_logo_style']['effects'] = array(
		array(
				// Name of the image effect. See image_image_effect_info() in
				// modules/image/image.effects.inc for a list of image effects available
				// in Drupal 7 core.
				'name' => 'image_scale',
				// Arguments to pass to the effect callback function.
				// The arguments that an effect accepts are documented with each
				// individual image_EFFECT_NAME_effect function. See image_scale_effect()
				// for an example.
				'data' => array(
						'width' => 142,
						'height' => 114,
						'upscale' => 0,
				),
				// The order in which image effects should be applied when using this
				// style.
				'weight' => 0,
		),
	);

	return $styles;
}

function drupal_projects_shortcut_default_set($account) {
	return variable_get('drupal_projects_shortcut_set_name');
}

// TODO set uri of taxonomy terms
// http://dropbucket.org/node/92

/**
 * alter the Content View Filter form
 */
function drupal_projects_preprocess_views_exposed_form(&$vars, $hook) {
	if ($vars['form']['#id'] == 'views-exposed-form-admin-views-node-system-1') {
		// Change the text on the submit button
		$vars['form']['submit']['#value'] = t('Search');
		// Rebuild the rendered version (submit button, rest remains unchanged)
		unset($vars['form']['submit']['#printed']);
		$vars['button'] = drupal_render($vars['form']['submit']);
	}
}

/**
 * preselect the project / profile
 * custom redirect after node delete
 */
function drupal_projects_form_alter(&$form, &$form_state, $form_id) {
	if (preg_match('/^(drupal_projects|personal_profile|ufal_tool)_page_node_form$/', $form_id)) {
		// Subpage
		$lang = $form['language']['#value'];
		$tx = array(
			'drupal_projects_page_node_form'  => 'drupal_projects_project',
			'personal_profile_page_node_form' => 'field_profile',
			'ufal_tool_page_node_form'        => 'field_project_term',
		);
		$project_field = @$tx[$form_id];
		
		if (is_numeric(arg(3))) {
			// preselected project
			$selected_project_tid = arg(3);
			$form[$project_field][$lang]['#default_value'] = $selected_project_tid;
		} else {
			$selected_project_tid = $form[$project_field][$lang]['#default_value'][0];
		}
		
		// display only parent pages that belong to current project
		$term = taxonomy_term_load($selected_project_tid);
		$project = _term_to_project($term);
		$menu_name = _project_to_menu_name($project);
		$pattern = '^' . $menu_name;
		foreach ($form['menu']['link']['parent']['#options'] as $key => $option) {
			if (!preg_match("/$pattern/", $key)) {
				unset($form['menu']['link']['parent']['#options'][$key]);
			}
		}
		
		if (is_numeric(arg(3))) {
			// enable menu creation by default
			$form['menu']['enabled']['#default_value'] = 1;
		}
		
		// hide
		$form[$project_field][$lang]['#disabled'] = true;
		$form[$project_field][$lang]['#type']     = 'value';
		$form['menu']['link']['weight']['#disabled']         = true;
		$form['menu']['link']['weight']['#type']             = 'value';
		$form['menu']['link']['description']['#disabled']    = true;
		$form['menu']['link']['description']['#type']        = 'value';
	}
	if ($form_id == 'node_delete_confirm' && preg_match('/^(drupal_projects|personal_profile|ufal_tool)$/', $form['#node']->type)) {
		$form['#submit'][] = '_custom_redirect_after_delete';
	}
	if ($form_id == 'drupal_projects_node_form' && (arg(1) == 'add' || arg(2) == 'edit')) {
		// create Drupal Project
		$form['drupal_projects_project']['#access'] = false;
	}
	if ($form_id == 'personal_profile_node_form' && (arg(1) == 'add' || arg(2) == 'edit')) {
		// create Personal Profile
		$form['field_profile']['#access'] = false;
		
		_wrap_form_field($form, 'field_main_research_interests');
		_wrap_form_field($form, 'field_curriculum_vitae');
		_wrap_form_field($form, 'field_selected_bibliography');
		//_wrap_form_field($form, 'body');
	}
	if ($form_id == 'ufal_tool_node_form' && (arg(1) == 'add' || arg(2) == 'edit')) {
		// create Ufal Tool
		$form['field_project_term']['#access'] = false;
	}
}
function _custom_redirect_after_delete($form, &$form_state) {
	// GET destination has precedence over $form_state['redirect']
	$_GET['destination'] = 'admin/my-content';
	drupal_static_reset('drupal_get_destination');
	$form_state['redirect'] = 'admin/my-content';
}
/**
 * collapse the 'Bulk Operations' form and put it down the page
 */
function drupal_projects_views_bulk_operations_form_alter(&$form, &$form_state, $vbo) {
	if ($form['#form_id'] =='views_form_admin_views_node_system_1') {
		$form['select']['#collapsed'] = TRUE;
		$form['select']['#weight'] = 100;
	}
	if ($form['#form_id'] =='views_form_admin_my_content_page') {
		$form['select']['#collapsed'] = TRUE;
		$form['select']['#weight'] = 100;
	}
	if ($form['#form_id'] =='views_form_admin_my_content_page_1') {
		$form['select']['#collapsed'] = TRUE;
		$form['select']['#weight'] = 100;
	}
}

/**
 * implements hook_preprocess_views_view
 * Wrap exposed filters in a fieldset. 
 */
function drupal_projects_preprocess_views_view(&$vars) {
	if ($vars['exposed']) {
		drupal_add_js('misc/form.js');
		drupal_add_js('misc/collapse.js');
		// Default collapsed
		$collapsed = TRUE;
		$class = array('collapsible', 'collapsed');
		// TODO, don't know how to detect selected filters
		if (0) {
			// assume other get vars are exposed filters, so expand fieldset
			// to show applied filters
			$collapsed = FALSE;
			$class = array('collapsible');
		}
		$fieldset['element'] = array(
				'#title' => t('Filter'),
				'#collapsible' => TRUE,
				'#collapsed' => $collapsed,
				'#attributes' => array('class' => $class),
				'#children' => $vars['exposed'],
		);
		$vars['exposed'] = theme('fieldset', $fieldset);
	}
}

/**
 * 
 */
function drupal_projects_menu_local_tasks_alter(&$data, $router_item, $root_path) {
	switch ($root_path){
		case 'admin/my-content':
			$out = array(
				'admin/tasks' => 1,
				'admin/index' => 1,
				'admin' => 1,
				'admin/index' => 1,
				'admin/workbench/sections' => 1,
				'admin/my-content-old-version' => 1,
			);
			foreach ($data['tabs'][0]['output'] as $i => &$tab) {
				if (@$out[$tab['#link']['path']]) {
					unset($data['tabs'][0]['output'][$i]);
				}
			}
			break;
		case 'admin/my-content/%':
			$current_path = current_path();
			
			if (preg_match('/admin\/my-content\/(\d+)/', $current_path, $matches)) {
				$project_tid = $matches[1];
			}
			if (!$project_tid) {
				break;
			}
			
			$term = taxonomy_term_load($project_tid);
			$project = _term_to_project($term);
			
			if ($project->type == 'drupal_projects') {
				_add_local_task($data, t('Add page to project'), 'node/add/drupal-projects-page', "/$project_tid");
				_add_local_task($data, t('Alter project menu'),  'admin/structure/menu/manage/' . _project_to_menu_name($project));
			}
			if ($project->type == 'personal_profile') {
				_add_local_task($data, t('Add page to personal profile'), 'node/add/personal-profile-page', "/$project_tid");
				_add_local_task($data, t('Alter menu'), 'admin/structure/menu/manage/' . _project_to_menu_name($project)); 
			}
			if ($project->type == 'ufal_tool') {
				_add_local_task($data, t('Add page to tool site'), 'node/add/ufal-tool-page', "/$project_tid");
				_add_local_task($data, t('Alter menu'), 'admin/structure/menu/manage/' . _project_to_menu_name($project));
			}
			
			break;
	}
}
function _add_local_task(&$data, $title, $destination, $href_suffix = null) {
	$item = menu_get_item($destination);
	if ($href_suffix) {
		$item['href'] .= $href_suffix;
	}
	$item['title'] = $title;
	if ($item['access']) {
		$data['actions']['output'][] = array(
				'#theme' => 'menu_local_action',
				'#link' => $item,
		);
	}
}

/**
 * Adding '+ New project' link into shortcut menu
 */
function drupal_projects_page_alter(&$page) {
  if (isset($page['page_top']['toolbar'])) {
    // If the toolbar is available, add a pre-render function to modify the
    // current shortcuts in the toolbar drawer.
    $page['page_top']['toolbar']['#pre_render'][] = 'drupal_projects_toolbar_pre_render';
  }
}
function drupal_projects_toolbar_pre_render($toolbar) {
	// turn the configure link into 'new project link'
	$toolbar['toolbar_drawer'][0]['configure']['#title'] = t('+ New project');
	$toolbar['toolbar_drawer'][0]['configure']['#href']  = 'node/add/drupal-projects';
	
	// another link there, just if theres no profile yet
	$toolbar['toolbar_drawer'][0]['configure2'] = $toolbar['toolbar_drawer'][0]['configure'];
	$toolbar['toolbar_drawer'][0]['configure2']['#title'] = t('+ Personal profile');
	$toolbar['toolbar_drawer'][0]['configure2']['#href']  = 'node/add/personal-profile';
	return $toolbar;
}
/**
 * Tie into workbench access
 */
function _workbench_access_allow_user_access_to_project($tid) {
	$account = $GLOBALS['user'];
	// Now check the user account.
	if (!isset($account->workbench_access)) {
		$account = user_load($account->uid);
	}
	$sections = @$account->workbench_access;
	if (!empty($account->workbench_access_by_role)) {
		foreach ($account->workbench_access_by_role as $key) {
			unset($sections[$key]);
		}
	}
	if (!empty($account->status) && !in_array($tid, array_keys((array)$sections))) {
		workbench_access_user_section_save($account->uid, $tid, variable_get('workbench_access'));
	}
}
/**
 * addding co-editors to own projects through 'Share' local task menu item
 */
function drupal_projects_menu() {
	$items['admin/my-content/%/editors'] = array(
			'title' => 'Share',
			'description' => 'Allow fellows to edit.',
			'page callback' => 'workbench_access_editors',
			'page arguments' => array('taxonomy', 2),
			'access callback' => 'drupal_projects_editors_menu_access',
			'access arguments' => array('taxonomy', 2),
			'type' => MENU_LOCAL_TASK,
			'weight' => 10,
			'file' => 'workbench_access.admin.inc',
			'file path' => drupal_get_path('module', 'workbench_access'),
	);
	$items['admin/my-content'] = array(
			'title' => 'My Content',
			'description' => 'List of editorial groups.',
			'page callback' => 'workbench_access_sections',
			'access arguments' => array('access workbench'),
			'type' => MENU_LOCAL_TASK,
			'weight' => 10,
			'file' => 'workbench_access.admin.inc',
			'file path' => drupal_get_path('module', 'workbench_access'),
	);
	
	return $items;
}
function drupal_projects_editors_menu_access() {
	$args = func_get_args();
	$project_tid = array_pop($args);
	$term = taxonomy_term_load($project_tid);
	//$term = array_pop($args);
	$account = $GLOBALS['user'];
	$project = _term_to_project($term);
	if (
	      user_access('assign workbench access')
	      // two options: just owner can share, or all editors can share
	      // editors check
	      //  || (user_access('assign workbench subaccess') && node_access('update', $project, $account))
	      // owner check
	      || (user_access('assign workbench subaccess') && $account->uid == $project->uid)
	) {
		return TRUE;
	}
	return FALSE;
}
/**
 * Hiding project links I have no access to
 */
function drupal_projects_menu_link_alter(&$link) {
	// please call hook_translated_menu_link_alter on my links
	if (preg_match('/admin\/my-content/', $link['link_path']) && $link['module'] == 'drupal_projects' && $link['menu_name'] == variable_get('drupal_projects_shortcut_set_name')) {
		$link['options']['alter'] = TRUE;
	}
}

function drupal_projects_translated_menu_link_alter(&$link) {
	$matches = array();
	if (preg_match('/admin\/my-content\/(\d+)/', $link['link_path'], $matches) && $link['module'] == 'drupal_projects' && $link['menu_name'] == variable_get('drupal_projects_shortcut_set_name')) {
		$project_tid = $matches[1];
		$account = $GLOBALS['user'];
		$term    = taxonomy_term_load($project_tid);
		$project = _term_to_project($term);
		// Now check the user account.
		if (!node_access('update', $project, $account)) {
			$link['hidden'] = 1;
		}
	}
}
/**
 * Utility functions
 * TODO namespace them? move to separate file?
 */

function _node_to_project($node) {
	$term    = _project_to_term($node);
	$project = _term_to_project($term);
	return $project; 
}
function _project_slug($title) {
	$t = get_t();
	module_load_include('inc', 'pathauto', 'pathauto');
	$slug = pathauto_cleanstring($t($title));
	if (strlen($slug) > 32) // 
		$slug = substr($slug, 0, 31);
	return $slug;
}
function _term_slug($title) {
	$t = get_t();
	module_load_include('inc', 'pathauto', 'pathauto');
	$slug = pathauto_cleanstring($t($title));
	if (strlen($slug) > 32) //
		$slug = substr($slug, 0, 31);
	return $slug;
}

function _project_to_term_tid($node) {
	if (!empty($node)) {
		//$tid  = @$node->drupal_projects_project[$node->language][0]['tid'];
		//return $tid;
		if ($project_ref = @$node->drupal_projects_project) {
			$project_term = array_shift($project_ref[$node->language]);
			return $project_term['tid'];
		}
		if ($project_ref = @$node->field_profile) {
			$project_term = array_shift($project_ref[$node->language]);
			return $project_term['tid'];
		}
	}
	return false;
}
function _project_to_term($node) {
	$tid  = _project_to_term_tid($node);
	$term = taxonomy_term_load($tid);
	return $term;
}
function _term_to_project($term) {
	// get all projects filled under this term
	$nodes = node_load_multiple(taxonomy_select_nodes($term->tid));
	// TODO BEWARE do not load all of them, filter them somehow!
	foreach ($nodes as $node) {
		if ($node->type == 'drupal_projects' || $node->type == 'personal_profile') {
			break;
		}
	}
	return $node;
	//$nodes = taxonomy_select_nodes($term->tid);
	//$node = node_load($nodes[0]);
	//$term_url = drupal_lookup_path('alias', 'node/'.$node->nid);
	
	
	// override the destination url
	// to the project home page!
	//$term_url = '';
	
}
function _project_to_menu($node) {
	$menu = _project_to_menu_array($node);
	if (menu_load($menu['menu_name'])) {
		return $menu;
	} else {
		return false;
	}
}
function _project_to_menu_array($project) {
	$t = get_t();
	$menu_array = array(
		'menu_name'   => _project_to_menu_name($project),
		'title'       =>  $t($project->title),
		'description' => 'This menu defines the core structure for the subsite '.$project->title.'. This is deleted along with any associated menu items when the subsite is deleted.',
		'module'      => 'drupal_projects',
	);
	return $menu_array;
}
function _project_to_menu_name($project) {
	return 'project-' . $project->nid . '-menu';
}
function _project_get_project_logo_uri($project) {
	if (!isset($project->drupal_projects_image[$project->language][0]['uri'])) {
		// default logo images are not populated for just referenced nodes (ie. not for main content)
		node_build_content($project);
	}
	return $project->drupal_projects_image[$project->language][0]['uri'];
}
function _project_to_acronym($project) {
	if (isset($project->field_acronym[$project->language][0]['value'])) {
		return $project->field_acronym[$project->language][0]['value'];
	}
	return $project->title;
}
function _project_get_shortcut_links($project_tid) {
	$result = db_query("SELECT * FROM {menu_links} WHERE link_path = :path AND module = 'drupal_projects'", array(':path' => 'admin/my-content/'.$project_tid), array('fetch' => PDO::FETCH_ASSOC));
	return $result;
}
function _project_get_url_aliases($project) {
	$project_slug = _project_slug(_project_to_acronym($project));
	$result = db_query("SELECT * FROM {url_alias} WHERE alias LIKE :alias", array(':alias'=>"$project_slug/%"), array('fetch' => PDO::FETCH_ASSOC));
	return $result;
}
function _wrap_form_field(&$form, $field_name) {
	$form['fieldsetted_' . $field_name] = array(
			'#title' => $form[$field_name][$form['language']['#value']]['#title'],
			'#type' => 'fieldset',
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
			'#weight' => $form[$field_name]['#weight'],
	);
	$form['fieldsetted_' . $field_name][$field_name] = $form[$field_name];
	unset($form[$field_name]);
}
function _project_to_vocabulary_id($node) {
	$tx = array(
		'drupal_projects'  => 'drupal_projects_vocabulary_id',
		'personal_profile' => 'profiles_vocabulary_id',
		'ufal_tool'       =>  'ufal_tool_vocabulary_id',
	);
	$var_name = @$tx[$node->type];
	if (!$var_name) {
		drupal_set_message('no vocabulary defined for ' . $node->type, 'warning');
	} 
	return variable_get($var_name);
}
